'use client';

import GlobalModal from '@/components/Modal/GlobalModal';
import GridLayout from '@/components/layout/grid-layout';
import MobileLayout from '@/components/layout/mobile-layout';
import ReactQueryProvider from '@/lib/react-query/ReactQueryProvider';
import StyledComponentsRegistry from '@/lib/registry';
import { GlobalStyle } from '@/styles/GlobalStyle';
import { theme } from '@/styles/theme';
import localFont from 'next/font/local';
import { RecoilRoot } from 'recoil';
import { ThemeProvider } from 'styled-components';

// export const metadata: Metadata = {
//   title: '맛셔너리',
//   description: 'Generated by create next app',
// };

const mainFont = localFont({
  src: '../assets/fonts/Galmuri9.woff2',
  display: 'swap',
  variable: '--Galmuri-9',
});

const subFont = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--Pretendard-Variable',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // 배포 환경에서 console.log, console.warn 지우기
  if (typeof window !== 'undefined' && process.env.NODE_ENV === 'production') {
    console = window.console || {};
    console.log = function no_console() {};
    console.warn = function no_console() {};
    console.error = function no_console() {};
  }

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
      </head>
      <body className={`${subFont.variable} ${mainFont.variable}`}>
        <StyledComponentsRegistry>
          <RecoilRoot>
            <ThemeProvider theme={theme}>
              <GlobalStyle />
              <GlobalModal />
              <ReactQueryProvider>
                <MobileLayout>
                  <GridLayout>{children}</GridLayout>
                </MobileLayout>
              </ReactQueryProvider>
            </ThemeProvider>
          </RecoilRoot>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
