name: build_and_push_dev

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > $HOME/.npmrc
          echo "@homekeeper89:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "npmrc_path=$HOME/.npmrc" >> "$GITHUB_ENV"

      - name: inject env
        run: |
          echo "ENV=dev" > .env
          echo "NEXT_PUBLIC_KAKAO_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_CLIENT_KEY }}" >> .env
          echo "NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_DEV_SERVER_URL=${{ secrets.NEXT_PUBLIC_DEV_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL=${{ secrets.NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_REFRESH_TOKEN=${{ secrets.NEXT_PUBLIC_REFRESH_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}" >> .env
          echo "NEXT_PUBLIC_SENTRY_AUTH_KEY=${{ secrets.NEXT_PUBLIC_SENTRY_AUTH_KEY }}" >> .env
          echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}" >> .env
          echo "NEXT_PUBLIC_TELEGRAM_TOKEN=${{ secrets.NEXT_PUBLIC_TELEGRAM_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_TELEGRAM_CHAT_ID=${{ secrets.NEXT_PUBLIC_TELEGRAM_CHAT_ID }}" >> .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/taste-client:latest
            ${{ secrets.DOCKER_REGISTRY }}/taste-client:${{ github.REF_NAME }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/taste-client:latest
          secret-files: |
            npmrc=${{ env.npmrc_path }}
          cache-to: type=inline
