name: build_and_push_dev

on:
  push:
    branches:
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@homekeeper89'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: inject env
        run: |
          echo "ENV=dev" > .env
          echo "NEXT_PUBLIC_KAKAO_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_CLIENT_KEY }}" >> .env
          echo "NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_DEV_SERVER_URL=${{ secrets.NEXT_PUBLIC_DEV_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL=${{ secrets.NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_REFRESH_TOKEN=${{ secrets.NEXT_PUBLIC_REFRESH_TOKEN }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/taste-client:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/taste-client:latest
          cache-to: type=inline
