name: build

on:
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > $HOME/.npmrc
          echo "@homekeeper89:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "" >> $HOME/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_V2 }}" >> $HOME/.npmrc
          echo "@taehoya:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "npmrc_path=$HOME/.npmrc" >> "$GITHUB_ENV"

      - name: Inject env
        run: |
          echo "ENV=dev" > .env
          echo "NEXT_PUBLIC_KAKAO_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_CLIENT_KEY }}" >> .env
          echo "NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_DEV_SERVER_URL=${{ secrets.NEXT_PUBLIC_DEV_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL=${{ secrets.NEXT_PUBLIC_SEARCH_IMAGE_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_ID=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_NAVER_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_NAVER_CLIENT_SECRET }}" >> .env
          echo "NEXT_PUBLIC_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_REFRESH_TOKEN=${{ secrets.NEXT_PUBLIC_REFRESH_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}" >> .env
          echo "NEXT_PUBLIC_SENTRY_AUTH_KEY=${{ secrets.NEXT_PUBLIC_SENTRY_AUTH_KEY }}" >> .env
          echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}" >> .env
          echo "NEXT_PUBLIC_TELEGRAM_TOKEN=${{ secrets.NEXT_PUBLIC_TELEGRAM_TOKEN }}" >> .env
          echo "NEXT_PUBLIC_TELEGRAM_CHAT_ID=${{ secrets.NEXT_PUBLIC_TELEGRAM_CHAT_ID }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_LOGIN_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_LOGIN_REDIRECT_URI }}" >> .env
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" >> .env

      - name: Build
        run: |
          yarn install
          yarn build
